### PR TITLE
fix(client): organization and formatting

### LINKED ISSUE #35: Missing parameter when vehicle is in depot
### Summary

on line 115 it has type == 'depot' its missing the garageInfo parameter

### Reproduction

1. get a vehicle
2. depot the vehicle
3. open the depot menu to see it says the vehicle is already out

### Expected behavior

get my car out of the depot

### Actual behavior

i didnt get my car out of the depot

### Additional context

https://github.com/Qbox-project/qbx_garages/blob/f149443a541d60c66adaa3e63ea353028679a574/client/main.lua#L114C4-L134C12

here is the lines just need to edit line 115 to be
```lua
if garageInfo.type == 'depot' then
```

### Current Version

1.0.0

### Custom Resources

N/A

### PR DESCRIPTION
**Pull request by MafewTM**
## Description

- Begin properly organizing the functions and applying the appropriate lua annotations
- Reformat all strings into `(''):format()`
- Should fix #35 
- Removes players being sent to nearest garage coords when kicked out of vehicle being placed into garage

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

File: client/main.lua [hunk 1]
```diff
@@ -2,6 +2,69 @@ local config = require 'config.client'
...
+---@param percent number
+---@return string
+local function getProgressColor(percent)
+    if percent >= 75 then
+        return ProgressColor.GREEN
+    elseif percent > 25 then
+        return ProgressColor.YELLOW
+    end
+
+    return ProgressColor.RED
```
Comment (Manason) [inline client/main.lua:21]: nit; I personally would add the else since the third option is related closely to the other two.

I only use the implied else when using guard clauses. Feel free to ignore this if you don't agree.

File: client/main.lua [hunk 2]
```diff
@@ -2,6 +2,69 @@ local config = require 'config.client'
...
+end
+
+---@enum StateLabels
+local StateLabels = {
+    OUT = 0,
+    GARAGED = 1,
+    IMPOUND = 2,
+}
```
Comment (Manason) [inline client/main.lua:29]: Love the use of enums.

File: client/main.lua [hunk 3]
```diff
@@ -2,6 +2,69 @@ local config = require 'config.client'
...
+local function getStateLabel(state)
+    if StateLabels.OUT == state then
+        return Lang:t('status.out')
+    elseif StateLabels.GARAGED == state then
+        return Lang:t('status.garaged')
+    elseif StateLabels.IMPOUND == state then
+        return Lang:t('status.impound')
+    end
+
+    return 'Unknown'
```
Comment (Manason) [inline client/main.lua:42]: This is an example where I think it's fine and appropriate for the implied else since 'Unknown' is a default value and therefore not as related to each other as the other 3.

File: client/main.lua [hunk 4]
```diff
@@ -2,6 +2,69 @@ local config = require 'config.client'
...
+end
+
+---@enum VehicleCategory
+local VehicleCategory = {
+    all = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22},
+    car = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 17, 18, 19, 20, 22},
+    air = {15, 16},
+    sea = {14},
+}
```
Comment (Manason) [inline client/main.lua:51]: I see you copied and pasted this so feel free to not address, but this isn't an enum and shouldn't be marked as such. Additionally, this should probably be a "set" table<integer, boolean> for O(1) lookup times. checkVehicleClass() can then be replaced by a lookup of the set to simplify the code as well.

**Review by Manason — APPROVED** [review]
Some minor nitpicks. Nothing that needs to be addressed in this PR.

File: client/main.lua (hunk 4 above)
Comment (MafewTM) [reply client/main.lua:51]: You've lost me on the set for O(1) lookup times
